/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AkCheck: typeof import('@kalimahapps/vue-icons/ak')['AkCheck']
    AkEyeOpen: typeof import('@kalimahapps/vue-icons/ak')['AkEyeOpen']
    AkEyeSlashed: typeof import('@kalimahapps/vue-icons/ak')['AkEyeSlashed']
    AkXSmall: typeof import('@kalimahapps/vue-icons/ak')['AkXSmall']
    AnOutlinedCopy: typeof import('@kalimahapps/vue-icons/an')['AnOutlinedCopy']
    AnOutlinedInfo: typeof import('@kalimahapps/vue-icons/an')['AnOutlinedInfo']
    BsX: typeof import('@kalimahapps/vue-icons/bs')['BsX']
    CoCopy: typeof import('@kalimahapps/vue-icons/co')['CoCopy']
    ReResetLeftLine: typeof import('@kalimahapps/vue-icons/re')['ReResetLeftLine']
  }
}
